import { pipeline, env } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm";
import { marked } from "https://cdn.jsdelivr.net/npm/marked@12/+esm";
env.allowRemoteModels = true; env.allowLocalModels = false; marked.setOptions({ breaks: true });
const $ = id => document.getElementById(id);
const loadBtn=$("loadBtn"),modelSelect=$("modelSelect"),progress=$("progress"),progressBar=progress.querySelector("i"),progressText=$("progressText");
const recordBtn=$("recordBtn"),recordStartBtn=$("recordStartBtn"),uploadBtn=$("uploadBtn"),audioUpload=$("audioUpload"),timerEl=$("timer"),state=$("state"),errorBox=$("error");
const historyList=$("historyList"),historyEmpty=$("historyEmpty"),noteCount=$("noteCount"),newNoteView=$("newNoteView"),recordView=$("recordView"),editorView=$("editorView"),processingStatus=$("processingStatus"),diskUsage=$("diskUsage"),diskUsageBar=$("diskUsageBar"),diskRemaining=$("diskRemaining");
const titleEl=$("noteTitle"),metaEl=$("noteMeta"),audioEl=$("noteAudio"),output=$("output"),summaryOutput=$("summaryOutput"),summaryPreview=$("summaryPreview"),summarizeBtn=$("summarizeBtn"),sumStatus=$("sumStatus"),sumProgress=$("sumProgress"),sumProgressBar=sumProgress.querySelector("i");
const DB_NAME="local-transcriber",STORE="recordings";
let transcriber,summarizer,recorder={state:"inactive"},stream,recorderContext,recorderSource,recorderProcessor,recorderSilencer,pcmChunks=[],isRecording=false,timerId,startedAt=0,stoppedAt=0,selectedNote=null,currentAudioUrl=null,saveTimer;
function db(mode,action){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:"id"})};req.onerror=()=>reject(req.error);req.onsuccess=()=>{const tx=req.result.transaction(STORE,mode),result=action(tx.objectStore(STORE));tx.oncomplete=()=>resolve(result?.result);tx.onerror=()=>reject(tx.error)}})}
const dbPut=note=>db("readwrite",store=>store.put(note)),dbDelete=id=>db("readwrite",store=>store.delete(id));
const dbGetAll=()=>new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:"id"})};req.onerror=()=>reject(req.error);req.onsuccess=()=>{const get=req.result.transaction(STORE,"readonly").objectStore(STORE).getAll();get.onsuccess=()=>resolve(get.result||[]);get.onerror=()=>reject(get.error)}})
function show(view){newNoteView.classList.toggle("hidden",view!=="new");recordView.classList.toggle("hidden",view!=="record");editorView.classList.toggle("hidden",view!=="editor")}
function showError(message){errorBox.textContent=message;errorBox.classList.remove("hidden")}function clearError(){errorBox.classList.add("hidden")}function setProcessing(label=""){processingStatus.textContent=label;processingStatus.classList.toggle("hidden",!label)}
function fmt(ms){const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function firstLine(text=""){return text.trim().split(/(?<=[.!?])\s|\n/)[0]?.slice(0,70)||""}function noteTitle(note){return note.title||firstLine(note.transcript)||"Untitled note"}function notePreview(note){return(note.summaryMarkdown||note.transcript||"No transcript yet").replace(/[#*_`\n-]+/g," ").replace(/\s+/g," ").trim()}function safeId(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function isMobileDevice(){return /Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia("(pointer:coarse)").matches}
async function pickDevice(){if(isMobileDevice())return "wasm";if(!("gpu"in navigator))return "wasm";try{return await navigator.gpu.requestAdapter()?"webgpu":"wasm"}catch{return "wasm"}}
async function releaseModel(ref){try{await ref?.dispose?.();await ref?.model?.dispose?.()}catch(err){console.warn("Model release failed",err)}}
async function loadModel(){loadBtn.disabled=true;modelSelect.disabled=true;progress.classList.remove("hidden");progressBar.style.width="2%";progressText.textContent="Preparing speech model…";try{const device=await pickDevice();transcriber=await pipeline("automatic-speech-recognition",modelSelect.value,{device,dtype:device==="webgpu"?"q4":"q8",progress_callback:p=>{if(typeof p?.progress==="number"){progressBar.style.width=`${Math.max(2,Math.min(100,p.progress))}%`;progressText.textContent=`${p.file||"Model"} · ${Math.round(p.progress)}%`}}});progressBar.style.width="100%";progressText.textContent="Speech model ready — it stays on this device.";loadBtn.textContent="Model ready"}catch(err){console.error(err);progressText.textContent="Could not load the speech model. Check your connection.";loadBtn.disabled=false;modelSelect.disabled=false}}
async function ensureTranscriber(){if(transcriber)return true;await loadModel();return Boolean(transcriber)}
async function ensureSummarizer(){if(summarizer)return true;sumProgress.classList.remove("hidden");sumProgressBar.style.width="2%";sumStatus.textContent="Downloading the private summary model…";try{if(isMobileDevice()&&transcriber){sumStatus.textContent="Freeing up memory before downloading the summary model…";await releaseModel(transcriber);transcriber=null;loadBtn.disabled=false;loadBtn.textContent="Load model"}const device=await pickDevice();summarizer=await pipeline("summarization","Xenova/distilbart-cnn-6-6",{device,dtype:device==="webgpu"?"q4":"q8",progress_callback:p=>{if(typeof p?.progress==="number")sumProgressBar.style.width=`${Math.max(2,Math.min(100,p.progress))}%`}});sumStatus.textContent="Summary model ready — runs on this device.";sumProgress.classList.add("hidden");return true}catch(err){console.error(err);sumStatus.textContent="Couldn't load the summary model. Try closing other tabs to free up memory, then try again.";sumProgress.classList.add("hidden");return false}}
function startTimer(){startedAt=Date.now();timerEl.textContent="00:00";timerId=setInterval(()=>timerEl.textContent=fmt(Date.now()-startedAt),200)}function stopTimer(){clearInterval(timerId);timerId=null}function makeWave(){$("wave").innerHTML=Array.from({length:48},()=>"<i></i>").join("")}function animateWave(){if(!isRecording)return;$("wave").querySelectorAll("i").forEach(bar=>bar.style.height=`${4+Math.random()*20}px`);requestAnimationFrame(animateWave)}makeWave();
async function openRecorder(){clearError();show("record");if(!await ensureTranscriber()){state.textContent="Load the speech model to record.";return}try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});recordBtn.disabled=false;recordBtn.textContent="●";state.textContent="Ready to record"}catch(err){console.error(err);state.textContent="Microphone unavailable";showError("Allow microphone access to record a note.")}}
function makeWav(samples,sampleRate){const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer),write=(offset,text)=>[...text].forEach((char,i)=>view.setUint8(offset+i,char.charCodeAt(0)));write(0,"RIFF");view.setUint32(4,36+samples.length*2,true);write(8,"WAVE");write(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,"data");view.setUint32(40,samples.length*2,true);samples.forEach((sample,i)=>view.setInt16(44+i*2,Math.max(-1,Math.min(1,sample))*32767,true));return new Blob([buffer],{type:"audio/wav"})}
async function startRecording(){if(!stream||isRecording)return;recorderContext=new AudioContext();recorderSource=recorderContext.createMediaStreamSource(stream);recorderProcessor=recorderContext.createScriptProcessor(4096,1,1);recorderSilencer=recorderContext.createGain();recorderSilencer.gain.value=.00001;pcmChunks=[];recorderProcessor.onaudioprocess=event=>pcmChunks.push(new Float32Array(event.inputBuffer.getChannelData(0)));recorderSource.connect(recorderProcessor);recorderProcessor.connect(recorderSilencer);recorderSilencer.connect(recorderContext.destination);await recorderContext.resume();isRecording=true;recorder.state="recording";startTimer();animateWave();recordBtn.classList.add("!bg-rose-600","shadow-rose-300/40");recordBtn.textContent="■";state.textContent="Recording…"}async function stopRecording(){if(!isRecording)return;isRecording=false;recorder.state="inactive";stoppedAt=Date.now();stopTimer();recordBtn.disabled=true;state.textContent="Saving full recording…";await new Promise(resolve=>setTimeout(resolve,120));recorderProcessor.disconnect();recorderSource.disconnect();recorderSilencer.disconnect();stream?.getTracks().forEach(track=>track.stop());stream=null;const sampleRate=recorderContext.sampleRate;await recorderContext.close();const length=pcmChunks.reduce((total,chunk)=>total+chunk.length,0),samples=new Float32Array(length);let offset=0;pcmChunks.forEach(chunk=>{samples.set(chunk,offset);offset+=chunk.length});if(!samples.length){showError("No microphone audio was captured. Check the input device and try again.");recordBtn.disabled=false;return}await createNoteFromAudio(makeWav(samples,sampleRate),stoppedAt-startedAt)}
async function decodeAudio(blob){const ctx=new AudioContext();try{const decoded=await ctx.decodeAudioData(await blob.arrayBuffer()),mono=new Float32Array(decoded.length);for(let channel=0;channel<decoded.numberOfChannels;channel++){const source=decoded.getChannelData(channel);for(let i=0;i<source.length;i++)mono[i]+=source[i]/decoded.numberOfChannels}if(decoded.sampleRate===16000)return{audio:mono,durationMs:Math.round(decoded.duration*1000)};const length=Math.max(1,Math.ceil(decoded.duration*16000)),offline=new OfflineAudioContext(1,length,16000),buffer=offline.createBuffer(1,mono.length,decoded.sampleRate);buffer.copyToChannel(mono,0);const source=offline.createBufferSource();source.buffer=buffer;source.connect(offline.destination);source.start();return{audio:(await offline.startRendering()).getChannelData(0),durationMs:Math.round(decoded.duration*1000)}}finally{await ctx.close()}}
async function createNoteFromAudio(blob,recordedDurationMs=0,suppliedTitle=""){if(!await ensureTranscriber())return;show("record");state.textContent="Transcribing on this device…";setProcessing("Transcribing locally");recordBtn.classList.remove("!bg-rose-600","shadow-rose-300/40");try{const{audio,durationMs}=await decodeAudio(blob),result=await transcriber(audio,{chunk_length_s:30,stride_length_s:5,return_timestamps:false}),transcript=(result?.text||"").trim(),note={id:safeId(),createdAt:Date.now(),updatedAt:Date.now(),durationMs:recordedDurationMs||durationMs,audioBlob:blob,model:modelSelect.value,transcript,title:suppliedTitle||firstLine(transcript)||"Untitled note",summaryMarkdown:null};await dbPut(note);selectedNote=note;await renderNotes();openNote(note)}catch(err){console.error(err);showError("Transcription failed. Try a shorter audio file or reload the speech model.");state.textContent="Ready to try again"}finally{setProcessing("")}}
async function renderNotes(){const notes=(await dbGetAll()).sort((a,b)=>(b.updatedAt||b.createdAt)-(a.updatedAt||a.createdAt));historyList.querySelectorAll(".note-item").forEach(el=>el.remove());historyEmpty.classList.toggle("hidden",notes.length>0);noteCount.textContent=notes.length;notes.forEach(note=>{const button=document.createElement("button");button.className=`note-item${note.id===selectedNote?.id?" active":""}`;button.innerHTML=`<b></b><span></span><small>${new Date(note.createdAt).toLocaleDateString([],{month:"short",day:"numeric"})} · ${fmt(note.durationMs||0)}</small>`;button.querySelector("b").textContent=noteTitle(note);button.querySelector("span").textContent=notePreview(note);button.addEventListener("click",()=>openNote(note));historyList.appendChild(button)})}
function openNote(note){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;saveCurrent()}selectedNote=note;show("editor");titleEl.value=noteTitle(note);output.value=note.transcript||"";summaryOutput.value=note.summaryMarkdown||"";metaEl.textContent=`${new Date(note.createdAt).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})} · ${fmt(note.durationMs||0)}`;if(currentAudioUrl)URL.revokeObjectURL(currentAudioUrl);if(note.audioBlob){currentAudioUrl=URL.createObjectURL(note.audioBlob);audioEl.src=currentAudioUrl;audioEl.classList.remove("hidden")}else audioEl.classList.add("hidden");renderSummary();renderNotes();updateStorageInfo()}
function renderSummary(){const markdown=summaryOutput.value.trim();summaryPreview.classList.toggle("empty",!markdown);summaryPreview.innerHTML=markdown?marked.parse(markdown):"A concise summary will appear here."}function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveCurrent,450)}async function saveCurrent(){if(!selectedNote)return;selectedNote.title=titleEl.value.trim()||"Untitled note";selectedNote.transcript=output.value;selectedNote.summaryMarkdown=summaryOutput.value||null;selectedNote.updatedAt=Date.now();await dbPut(selectedNote);renderNotes()}
const SUM_CHUNK_CHARS=3000,SUM_MAX_CHUNKS=12;
function chunkText(text,maxChars=SUM_CHUNK_CHARS){const sentences=text.split(/(?<=[.!?])\s+/);const chunks=[];let current="";for(const sentence of sentences){if(current&&current.length+sentence.length+1>maxChars){chunks.push(current.trim());current=""}current+=(current?" ":"")+sentence}if(current.trim())chunks.push(current.trim());return chunks.length?chunks:[text]}
async function summarizeChunk(text,maxNewTokens=100,minNewTokens=20){const result=await summarizer(text,{max_new_tokens:maxNewTokens,min_new_tokens:minNewTokens});return result?.[0]?.summary_text?.trim()||""}
async function summarize(){if(!output.value.trim()||!selectedNote||!await ensureSummarizer())return;summarizeBtn.disabled=true;summarizeBtn.textContent="Summarizing…";setProcessing("Summarizing locally");sumProgress.classList.remove("hidden");sumProgressBar.style.width="2%";try{let chunks=chunkText(output.value.trim());let truncated=false;if(chunks.length>SUM_MAX_CHUNKS){chunks=chunks.slice(0,SUM_MAX_CHUNKS);truncated=true}const partials=[];for(let i=0;i<chunks.length;i++){sumStatus.textContent=chunks.length>1?`Summarizing part ${i+1} of ${chunks.length}…`:"Summarizing…";const partial=await summarizeChunk(chunks[i],chunks.length>1?90:120,20);if(partial)partials.push(partial);sumProgressBar.style.width=`${Math.round((i+1)/chunks.length*(chunks.length>1?70:100))}%`}let finalText;if(partials.length>1){sumStatus.textContent="Combining summary…";const combined=partials.join(" ");finalText=combined.length>SUM_CHUNK_CHARS?(await Promise.all(chunkText(combined).map(c=>summarizeChunk(c,90,15)))).join(" "):await summarizeChunk(combined,140,30);sumProgressBar.style.width="100%"}else{finalText=partials[0]||""}summaryOutput.value=`## Key points\n\n${finalText}${truncated?"\n\n*(Summary covers the first part of a very long transcript.)*":""}`;renderSummary();await saveCurrent();sumStatus.textContent="Summary model ready — runs on this device."}catch(err){console.error(err);showError("Summarization failed. Try a shorter transcript.")}finally{summarizeBtn.disabled=false;summarizeBtn.textContent="Summarize";setProcessing("");sumProgress.classList.add("hidden")}}
function formatStorage(bytes){if(!Number.isFinite(bytes))return "—";const units=["B","KB","MB","GB"],index=Math.min(units.length-1,Math.floor(Math.log(Math.max(bytes,1))/Math.log(1024)));return `${(bytes/1024**index).toFixed(index?1:0)} ${units[index]}`}async function updateStorageInfo(){if(!navigator.storage?.estimate){diskUsage.textContent="Storage estimate unavailable";diskUsageBar.style.width="0%";diskRemaining.textContent="Nothing leaves this device";return}try{const{usage=0,quota=0}=await navigator.storage.estimate(),remaining=Math.max(0,quota-usage),percent=quota?Math.min(100,usage/quota*100):0;$("storageInfo").textContent=quota?`${formatStorage(usage)} used`:"";diskUsage.textContent=`${formatStorage(usage)} used`;diskUsageBar.style.width=`${percent}%`;diskRemaining.textContent=quota?`${formatStorage(remaining)} remaining`:"Storage available"}catch{diskUsage.textContent="Storage estimate unavailable";diskUsageBar.style.width="0%";diskRemaining.textContent="Nothing leaves this device"}}function newNote(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;saveCurrent()}selectedNote=null;if(recorder?.state==="recording")stopRecording();show("new");renderNotes()}
$("newNoteBtn").addEventListener("click",newNote);recordStartBtn.addEventListener("click",openRecorder);recordBtn.addEventListener("click",()=>recorder?.state==="recording"?stopRecording():startRecording());uploadBtn.addEventListener("click",()=>audioUpload.click());audioUpload.addEventListener("change",async()=>{const file=audioUpload.files[0];audioUpload.value="";if(file)await createNoteFromAudio(file,0,file.name.replace(/\.[^/.]+$/,""))});$("settingsBtn").addEventListener("click",()=>{$("modelCard").open=!$("modelCard").open});loadBtn.addEventListener("click",loadModel);titleEl.addEventListener("input",queueSave);output.addEventListener("input",queueSave);summaryOutput.addEventListener("input",()=>{renderSummary();queueSave()});summarizeBtn.addEventListener("click",summarize);$("toggleSumViewBtn").addEventListener("click",()=>{const edit=summaryOutput.classList.toggle("hidden");summaryPreview.classList.toggle("hidden",!edit);$("toggleSumViewBtn").textContent=edit?"Edit":"Preview"});$("copyBtn").addEventListener("click",()=>navigator.clipboard.writeText(output.value));$("copySumBtn").addEventListener("click",()=>navigator.clipboard.writeText(summaryOutput.value));function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}$("downloadTxtBtn").addEventListener("click",()=>download(output.value,`${noteTitle(selectedNote)}.txt`,"text/plain"));$("downloadSumTxtBtn").addEventListener("click",()=>download(summaryOutput.value,`${noteTitle(selectedNote)}.md`,"text/markdown"));$("deleteNoteBtn").addEventListener("click",async()=>{if(selectedNote&&confirm("Delete this note?")){await dbDelete(selectedNote.id);selectedNote=null;newNote();await renderNotes()}});
renderNotes();updateStorageInfo();
